### ISSUE TITLE
Shortcut for Visual Block mode

### ISSUE THREAD

**Issue by ghost** [jooize/vim-colemak#8]
Hi, I like your configuration and am using it since I started to use colemak.

I don't usually use visual block mode, but I once tried it by pressing <C-A> as I expected, finding it doesn't work. <C-V> is the only shortcut I found to get into visual block mode. Is it the only way for it or does <C-A> shortcut causes any conflict with other keys?

**Comment by loudcolour** [comment]
@@ 1:5-1:7
- I'm
+ I

**Comment by jooize** [comment]
Press Control–V in Normal mode for Visual Block mode.

> `(  n  x)  a = v (Visual)   A = V (Visual line)`

It's not documented, apparently! Thanks for mentioning.
